book/urls.py
from django.urls import path , include

from .views import (home_page ,
	detail_book ,
	search ,
	detail_author)

urlpatterns = [
    path('' , home_page),
	path('book-detail/<int:article_id>/' , detail_book ),
	path('about-author/<int:author_id>/' , detail_author ),
	path('search/' , search ),
]

eshop/urls.py
from django.contrib import admin
from django.urls import path , include

from book.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('book.urls')),
    path('calcusdasdasdasdasdasde/' , include('examples.urls' , namespace='example')),
    path('users/' , include('users.urls' , namespace='client_app'))
]

examples/urls.py
from django.urls import path , include
from .views import calc_page , exchange , test_form

app_name  = 'example'

urlpatterns = [
    path('calculator/' , calc_page , name='calc'),
    path('exchange/' , exchange),
    path('asdasdasd-asdasdasdasd/' , test_form , name='form')
]

users/urls.py
from django.urls import path , include
from .auth_views import login_ , register_ , logout_
app_name  = 'client_app'



urlpatterns = [
   path('login/' , login_ , name='login'),
   path('register/' , register_ , name='register'),
   path('logout/' , logout_ , name='logout'),
]

book/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
	name = models.CharField(max_length=255, verbose_name='Имя автора')
	surname = models.CharField(max_length=255, verbose_name='Фамилия автора')
	nickname = models.CharField(max_length=255, verbose_name='Никнейм')
	date_birth = models.DateField()
	date_dead = models.DateField(blank=True, null=True)  # NULL

	def __str__(self):
		return f'{self.id} : {self.surname} {self.name}'

	def get_full_name(self):
		return '{name} {surname}'.format(name=self.name.upper() , surname=self.surname.upper())


	def get_books(self):
		return Book.objects.filter(author=self)

	def is_sales_books(self):
		return self.get_books().filter(is_sale=True)

	def is_not_sales_books(self):
		return self.get_books().filter(is_sale=False)

	def get_total_price(self):
		return sum([book.new_price for book in self.is_sales_books()] + \
	[book.price for book in self.is_not_sales_books()])

	def get_total_sales(self):
		all_price_is_sale  = sum([book.new_price for book in self.is_sales_books()])
		all_price_books  = sum([book.price for book in self.get_books()])
		return all_price_books - all_price_is_sale


class Book(models.Model):
	GENRE_CHOICE = (
		('comedy', 'Комедия'),
		('mistika', 'Мистика')
	)
	author = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)
	title = models.CharField(max_length=100)
	price = models.FloatField()
	description = models.TextField(max_length=100)
	is_sale = models.BooleanField(default=False)
	new_price = models.FloatField(default=0)
	genre = models.CharField(choices=GENRE_CHOICE, max_length=15, null=True)  # NULL


	def sales(self):
		if self.is_sale:
			return self.price - self.new_price

	def __str__(self):
		return 'title - {} price - {}'.format(self.title, self.price)

examples/models.py
from django.db import models


# Create your models here.

class Example(models.Model):
	CHOICE = (('1', 'option 1'), ('2', 'option 2'), ('3', 'option 3'),)
	int_field = models.IntegerField()
	float_field = models.FloatField()
	date_field = models.DateTimeField()
	char_field = models.CharField(max_length=255)
	text_field = models.TextField(max_length=1500)
	choice_field = models.CharField(choices=CHOICE , max_length=3)
	image_field = models.ImageField(upload_to='images/')
	file_field = models.FileField(upload_to='files/')
	bool_field = models.BooleanField()

	def __str__(self):
		return self.char_field

users/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class UserAuthor(models.Model):
	TYPE_CHOICE = (('fio', 'ФИО'), ('nickname', 'Псевдоним'),)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.TextField(max_length=1500, blank=True, null=True)
	nickname = models.CharField(max_length=255, blank=True, null=True)
	type_user_view = models.CharField(choices=TYPE_CHOICE,
		max_length=len('nickname'),
		blank=True, null=True)

	__str__ = lambda self: self.user.username

	class Meta:
		verbose_name = 'Автор'
		verbose_name_plural = 'Авторы'

examples/forms.py
from django import forms
from .models import Example

class ExampleForm(forms.ModelForm):
	class Meta:
		model = Example
		fields = '__all__'
		# exclude = ['date_field']
		# fields = ['int_field' , 'char_field']

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import UserAuthor
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
	first_name  = forms.CharField(max_length=100 , label='Имя' , required=True)
	last_name  = forms.CharField(max_length=100 , label='Фамилия' , required=True)
	email = forms.EmailField(max_length=255)


	def save(self , *args , **kwargs):
		data  = self.cleaned_data
		django_user  = User.objects.create_user(
			username=data['username'],
			password=data['password1'],
			first_name =data['first_name'],
			last_name =data['last_name'],
			email=data['email'],
			is_active  = True
		)
		UserAuthor.objects.create(user=django_user)
		print('save custom method!!!')
		return django_user

book/views.py
from django.shortcuts import render
from .models import Book , Author


# Create your views here.


def home_page(request):
    all_books = Book.objects.all() # select * from book_book;
    genres  = Book.GENRE_CHOICE
    return render(request, 'book/main.html', {
        'books': all_books,
        'genres': genres,
    })



def detail_book(request , article_id):
    ctx  = {}
    book  = Book.objects.get(id=article_id)
    ctx['book'] = book
    return render(request , 'book/detail_book.html' , ctx)


def detail_author(request , author_id):
    ctx  = {}
    author  = Author.objects.get(pk=author_id)
    # all_books = author.get_books()
    # filter_book = [book for book in all_books if book.is_sale]
    # print('filter_book ' , filter_book)
    ctx['author'] = author
    # ctx['all_books'] = all_books
    return render(request , 'book/detail_author.html' , ctx)


def search(request):
    ctx  = {}
    genre = request.GET.get('genre')
    from_price = int(request.GET.get('from_price'))
    to_price = int(request.GET.get('to_price'))
    books = Book.objects.filter(genre=genre)
    range_price  = range(from_price , to_price+1)
    new_list_book = []
    for book in books:
        if book.is_sale:
            if round(book.new_price) in range_price:
                new_list_book.append(book)
        else:
            if round(book.price) in range_price:
                new_list_book.append(book)
    ctx['books'] = new_list_book
    # ctx['new_list_book'] = new_list_book
    ctx['genres'] = Book.GENRE_CHOICE
    return render(request , 'book/main.html' , ctx)

examples/views.py
from django.shortcuts import render

# Create your views here.


calc_obj = {
	'+': lambda x, y : x + y,
	# '-': lambda x, y : x - y,
	# '*': lambda x, y : x * y,
	'/': lambda x, y : x / y
}

def calc_page(request):
	ctx = {'tab': 'calc'}
	ctx['operations'] = calc_obj.keys()
	try:
		first_number  = float(request.GET.get('first_number'))
		oper  = request.GET.get('oper').strip()
		second_number  = float(request.GET.get('second_number'))
		result  = calc_obj[oper](first_number , second_number)
		ctx['result'] = f'{first_number} {oper} {second_number} = {result}'
	except Exception as e:
		ctx['error'] = e
		print(type(e) , e)
	return render(request , 'examples/calc_page.html' , ctx)


import requests as R

API_URL  = 'https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5'
def exchange(request):
	ctx  = {}
	currency = request.POST.get('currency')
	count = float(request.POST.get('count'))
	print(currency , count)
	response  = R.get(API_URL).json()
	for res in response:
		if res.get('ccy') == currency:
			result = float(res.get('sale')) * count
			ctx['result'] = f"Вот столько {round(result,2)}  грн тебе нужно потратить на покупку"
			break
	return render(request , 'examples/calc_page.html' , ctx)

from .forms import ExampleForm

def test_form(request):
	ctx = {}
	ctx['form'] = ExampleForm()
	# if request.method  == 'GET':
	if request.method == 'POST':
		form  = ExampleForm(request.POST , request.FILES)
		if form.is_valid():
			form.save()
		else:
			ctx['form'] = ExampleForm(request.POST , request.FILES)
	return render(request , 'examples/test_form.html' , ctx)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/book/detail_author.html
{% extends 'index.html' %}

{% block content %}
    <h1>Страница автора {{author.get_full_name}}</h1>
    <p>Информация по автору</p>
    <p>Никнейм  - {{ author.nickname }}</p>
    <p class="alert alert-info">
        {{ author.date_birth }} -
        {% if author.date_dead %}
            {{ author.date_dead }}
        {% else %}
            По текущее время
        {% endif %}
    </p>
    <h3>Все книги данного автора</h3>

    <div class="row">
        {% for book in author.get_books %}
            <div class="col-md-3">
                <p> Название книги {{ book.title }}</p>
                <div>
                    {% if book.is_sale %}
                        <p class="alert alert-success">Книга по акции {{ book.new_price }}. Вы экономите {{ book.sales }} $ </p>
                    {% else %}
                    <p class="alert alert-danger">
                        Книга не по акции {{ book.price }}
                    </p>
                    {% endif %}
                </div>
                <a href="/book-detail/{{book.id}}/" class="btn btn-link">Подробнее</a>
                <a class="btn btn-primary" href="">Добавить в корзину</a>
                <a class="btn btn-info" href="">купить</a>
            </div>
        {% endfor %}
    </div>
<br>
<div class="row">
    <div class="col-md-6">Кол-во книг по акции  - {{ author.is_sales_books | length }}</div>
    <div class="col-md-6"> Кол-во книг не по акции  - {{ author.is_not_sales_books | length }} </div>
</div>
<br>
<br>
<br>
<a class="btn btn-warning" href="">Купить все книги данного автора</a>
<span>Покупая все книги данного автора за {{author.get_total_price}} $ , Вы экономите - {{ author.get_total_sales }} $</span>
{% endblock %}

templates/book/detail_book.html
{% extends 'index.html' %}

{% block content %}
    <h1>Page detail book!</h1>
    <h2 class="alert alert-info">{{ book.title }}</h2>
    <h3>
        <a href="/about-author/{{ book.author.id }}/">{{ book.author.get_full_name }}</a>
    </h3>
    {% if book.is_sale %}
        <p class="alert alert-success">
                Книга по акции!
        </p>
                <p>Старая  цена - {{ book.price }} $</p>
                <p>Новая цена - {{ book.new_price }} $</p>
                <p>Вы экономите {{ book.sales }} $</p>
    {% else  %}
        <p>Цена  - {{ book.price }} $ </p>
    {% endif %}
<div>
    Описание  - {{ book.description }}
</div>

{% if book.genre %}
    <div>
        Жанр  - {{ book.get_genre_display }}
    </div>
{% endif %}

<a class="btn btn-primary" href="">Добавить в корзину</a>
                <a class="btn btn-info" href="">купить</a>

{% endblock %}

templates/book/main.html
{% extends 'index.html' %}


{% block content %}
 <form class="form-inline" action="/search/">
  <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Жанр</label>
  <select class="custom-select my-1 mr-sm-2" name="genre" id="inlineFormCustomSelectPref">
      {% for genre in genres %}
            <option value="{{genre.0}}">{{genre.1}}</option>
      {% endfor %}
  </select>

  <div class="custom-control  my-1 mr-sm-2">
    От <input type="number" class="" name="from_price">
    До <input type="number" class="" name="to_price">
  </div>

  <button type="submit" class="btn btn-primary my-1">Search .... </button>
</form>
<div class="row">


    {% for book in books %}

    <div class="col-md-3" style="margin-bottom: 15px;">
        <p>id  - {{book.id}}</p>
        <p>Название - {{book.title}}</p>
        <p>Цена - {{book.price}}</p>
        <p>Описание -{{book.description}}</p>
        <a class="btn btn-primary" href="/book-detail/{{book.id}}/">Read more</a>
    </div>

    {% endfor %}
</div>

{% endblock %}

templates/examples/calc_page.html
{% extends 'index.html' %}


{% block content %}
<h1>Calculator!!</h1>

<!--    text <input type="text"> <br>-->
<!--    number <input type="number"> <br>-->
<!--    checkbox <input type="checkbox"> <br>-->
<!--    search <input type="search"> <br>-->
<!--    submit <input type="submit"> <br>-->
<!--    password <input type="password"> <br>-->
<!--    textarea<textarea name="" id="" cols="30" rows="10"></textarea> <br>-->
<!--    <select name="" id="">-->
<!--        <option value="">option 1 </option>-->
<!--        <option value="">option 2</option>-->
<!--        <option value="">option 3</option>-->
<!--    </select>-->
<form class="needs-validation" action="/examples/calculator/" method="get">

    <div class="form-row">
        <div class="col-md-6 mb-3">
            <label for="validationCustom03"> first number</label>
            <input type="number" name="first_number"
                   class="form-control" id="validationCustom03" required>
            <div class="invalid-feedback">
                first number
            </div>
        </div>
        <div class="col-md-3 mb-3">
            <label>Operation</label>
            <select name="oper" class="custom-select">
                {% for oper in operations %}
                <option value="{{ oper }}">{{oper}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-3 mb-3">
            <label for="validationCustom05">Second number</label>
            <input type="number" name="second_number" class="form-control" id="validationCustom05" required>
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Calc!</button>
</form>

{% if result %}
<div class="alert alert-success" role="alert">
    {{ result }}
</div>
{% endif %}

{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endif %}


<form action="/examples/exchange/" method="post">
    {% csrf_token %}
    <div class="form-row">
         <div class="col-md-3 mb-3">
      <label>Currency</label>
      <select name="currency" class="custom-select">
                <option value="USD">$</option>
                <option value="EUR">eu</option>
      </select>
    </div>
        <div class="col-md-6 mb-3">
            <label for="validationCustom03"> Сколько ты хочешь купить валюты?</label>
            <input type="text" name="count"
                   class="form-control" required>
        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="Calc!" >
    <input type="reset" class="btn btn-info" value="Reset form!" >
</form>


<!--<div class="alert alert-primary" role="alert">-->
<!--  A simple primary alert—check it out!-->
<!--</div>-->
<!--<div class="alert alert-secondary" role="alert">-->
<!--  A simple secondary alert—check it out!-->
<!--</div>-->
<!--<div class="alert alert-success" role="alert">-->
<!--  A simple success alert—check it out!-->
<!--</div>-->
<!--<div class="alert alert-danger" role="alert">-->
<!--  A simple danger alert—check it out!-->
<!--</div>-->
<!--<div class="alert alert-warning" role="alert">-->
<!--  A simple warning alert—check it out!-->
<!--</div>-->
<!--<div class="alert alert-info" role="alert">-->
<!--  A simple info alert—check it out!-->
<!--</div>-->
<!--<div class="alert alert-light" role="alert">-->
<!--  A simple light alert—check it out!-->
<!--</div>-->
<!--<div class="alert alert-dark" role="alert">-->
<!--  A simple dark alert—check it out!-->
<!--</div>-->
<!--<button type="button" class="btn btn-primary">Primary</button>-->
<!--<button type="button" class="btn btn-secondary">Secondary</button>-->
<!--<button type="button" class="btn btn-success">Success</button>-->
<!--<button type="button" class="btn btn-danger">Danger</button>-->
<!--<button type="button" class="btn btn-warning">Warning</button>-->
<!--<button type="button" class="btn btn-info">Info</button>-->
<!--<button type="button" class="btn btn-light">Light</button>-->
<!--<button type="button" class="btn btn-dark">Dark</button>-->

<!--<button type="button" class="btn btn-link">Link</button>-->
{% endblock %}

templates/examples/test_form.html
{% extends 'index.html' %}


{% block content %}
<h1>Test form page!!!!</h1>
<form action="." method="post" enctype="multipart/form-data"> {% csrf_token %}
    {% for field in form %}
    <div class="form-row">
        <label for="">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
            {% for err in field.errors %}
                <p style="color:red;" >{{ err }}</p>
            {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <button class="btn btn-success">Submit</button>
</form>
<!--{{ form.as_ul }}-->
{% endblock %}

templates/includes/footer.html
<footer>
    footer!
</footer>

templates/includes/header.html
<header>
    <!--    <a href="/">-->
    <!--        Go to homepage!-->
    <!--&lt;!&ndash;    </a>&ndash;&gt;-->
    <!--    {% if tab != 'calc' %}-->
    <!--    <a href="/examples/calculator/">-->
    <!--        Calculator-->
    <!--    </a>-->
    <!--    {% endif %}-->


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Examples
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/calculator-page/calculator/">Calculator</a>
                        <a class="dropdown-item" href="{% url 'example:form' %}">test-form</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>

            {% if request.user.is_authenticated %}
            <a href="{% url 'client_app:logout' %}" class="btn btn-danger">Выйти ({{ request.user.username }})</a>
            <a href="" class="btn btn-warning">Кабинет </a>
            {% else %}


            <a class="btn btn-primary" href="{% url 'client_app:login' %}">
                Авторизация
            </a>
            <a class="btn btn-primary" href="{% url 'client_app:register' %}">
                Регистрация
            </a>
            {% endif %}
        </div>
    </nav>
</header>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

{% include 'includes/header.html' %}

<div class="container">
{% block content %}

{% endblock %}
</div>
{% include 'includes/footer.html' %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>